packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': 1.5.4
  '@logtape/logtape': ^2.0.4
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@polar-sh/better-auth': ^1.8.2
  '@tanstack/react-form': ^1.28.4
  '@tanstack/react-query': ^5.90.21
  react: 19.2.4
  react-dom: 19.2.4
  '@types/node': ^25.4.0
  better-auth: 1.5.4
  dotenv: ^17.3.1
  hono: ^4.12.7
  typescript: ^5
  vite: ^7.3.1
  vitest: ^4.0.18
  zod: ^4.3.6
