packages:
  - apps/*
  - packages/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude: []
blockExoticSubdeps: true

overrides:
  '@babel/types': ^7.29.0
  '@vitejs/plugin-react': ^6.0.0
  vite-node: ^6.0.0

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  spawn-sync: true

catalog:
  '@base-ui/react': ^1.6.0
  '@better-auth/expo': 1.6.23
  '@logtape/logtape': ^2.2.3
  '@orpc/client': ^1.14.3
  '@orpc/openapi': ^1.14.3
  '@orpc/server': ^1.14.3
  '@orpc/tanstack-query': ^1.14.3
  '@orpc/zod': ^1.14.3
  '@polar-sh/better-auth': ^1.8.4
  '@tailwindcss/vite': ^4.3.2
  '@tanstack/react-form': ^1.33.0
  '@tanstack/react-query': ^5.101.2
  '@types/node': ^26.1.0
  '@types/pg': ^8.20.0
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  better-auth: 1.6.23
  dexie: ^4.4.4
  dexie-react-hooks: ^4.4.0
  dotenv: ^17.4.2
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  hono: ^4.12.18
  i18next: ^26.3.4
  lucide-react: ^1.23.0
  next-themes: ^0.4.6
  pg: ^8.22.0
  react: 19.2.6
  react-dom: 19.2.6
  shadcn: ^4.13.0
  sonner: ^2.0.5
  tailwindcss: ^4.3.2
  tw-animate-css: ^1.2.5
  typescript: ~6.0.3
  vite: ^8.1.3
  vitest: ^4.1.6
  zod: ^4.4.3
