#!/usr/bin/env sh
set -e

pnpm check
pnpm check-types
pnpm check:i18n
pnpm build
pnpm test
pnpm --filter @pengana/e2e e2e:web
pnpm --filter @pengana/e2e e2e:native
pnpm --filter @pengana/e2e e2e:extension
